@api = http://localhost:3000

54:50

GET http://localhost:3000/articulos

###

GET http://localhost:3000/articulos/1

###
put http://localhost:3000/articulos/1

### crear video

POST {{api}}/articulos
Content-Type: application/json

{
   "nombre": "Black Hanya",
    "tipo": "sudadera",
    "color": "negro",
    "existencias": true,
    "precio": {
        "$numberDecimal": "39.90"
    },
    "oferta": true
}



